trigger:
- main

pool:
  name: Default  # Make sure this matches your agent pool

strategy:
  matrix:
    Python38:
      pythonPath: $(HOME)/python38/bin/python3
    Python39:
      pythonPath: $(HOME)/python39/bin/python3
    Python310:
      pythonPath: $(HOME)/python310/bin/python3
    Python311:
      pythonPath: $(HOME)/python311/bin/python3

steps:
- script: |
    echo "Using Python at: $(pythonPath)"
    $(pythonPath) --version
  displayName: 'Verify Python version'

- script: |
    $(pythonPath) -m pip install --upgrade pip
    $(pythonPath) -m pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    $(pythonPath) -m pip install pytest
    $(pythonPath) -m pytest
  displayName: 'Run tests'
