trigger:
- main

pool:
  name: Default  # Use your agent pool name

jobs:
- job: TestMatrix
  displayName: Run tests for multiple Python versions
  pool:
    name: Default
    demands:
      - Agent.OS -equals Linux

  strategy:
    matrix:
      Python38:
        pythonPath: /home/gabriel_chiappa/python/3.8/bin/python3
      Python39:
        pythonPath: /home/gabriel_chiappa/python/3.9/bin/python3
      Python310:
        pythonPath: /home/gabriel_chiappa/python/3.10/bin/python3
      Python311:
        pythonPath: /home/gabriel_chiappa/python/3.11/bin/python3

  steps:
  - checkout: self

  - task: CmdLine@2
    displayName: 'Verify Python version'
    inputs:
      script: |
        echo "Using Python at: $(pythonPath)"
        $(pythonPath) --version

  - task: CmdLine@2
    displayName: 'Install dependencies'
    inputs:
      script: |
        echo "Installing dependencies"
        $(pythonPath) -m pip install --upgrade pip
        $(pythonPath) -m pip install -r requirements.txt

  - task: CmdLine@2
    displayName: 'Run tests with pytest'
    inputs:
      script: |
        $(pythonPath) -m pip install pytest
        $(pythonPath) -m pytest
