trigger:
- main

pool:
  name: Default

strategy:
  matrix:
    Python38:
      pythonPath: 'C:\Python38\python.exe'
    Python39:
      pythonPath: 'C:\Python39\python.exe'
    Python310:
      pythonPath: 'C:\Python310\python.exe'
    Python311:
      pythonPath: 'C:\Python311\python.exe'

steps:
- script: |
    $(pythonPath) -m pip install --upgrade pip
    $(pythonPath) -m pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    $(pythonPath) -m pip install pytest
    $(pythonPath) -m pytest
  displayName: 'Run tests'
