trigger:
- main

pool:
  name: Default  # your self-hosted agent pool

strategy:
  matrix:
    Python38:
      pythonPath: 'C:\Users\Gabriel\AppData\Local\Programs\Python\Python38\python.exe'
    Python39:
      pythonPath: 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\python.exe'
    Python310:
      pythonPath: 'C:\Users\Gabriel\AppData\Local\Programs\Python\Python310\python.exe'
    Python311:
      pythonPath: 'C:\Users\Gabriel\AppData\Local\Programs\Python\Python311\python.exe'

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo Using Python: "$(pythonPath)"
      "$(pythonPath)" --version
    workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Verify Python version'

- task: CmdLine@2
  inputs:
    script: |
      "$(pythonPath)" -m pip install --upgrade pip
      "$(pythonPath)" -m pip install -r requirements.txt
    workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Install dependencies'

- task: CmdLine@2
  inputs:
    script: |
      "$(pythonPath)" -m pip install pytest
      "$(pythonPath)" -m pytest
    workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Run tests'
